### ISSUE TITLE
Problem with lighttable

### ISSUE THREAD

**Issue by pjagielski** [venantius/ultra#19]
Since I added ultra to `~/.lein/profiles.clj` I got following error:

Don't know what's the correlation with ultra, but removing it solves the problem...

```
Exception in thread "main" java.lang.ClassNotFoundException: lighttable.nrepl.core, compiling:(/private/var/folders/mr/8_72b3r13631y6hwx2d78y20l118w9/T/form-init6025032780506562061.clj:1:1250)
    at clojure.lang.Compiler.analyze(Compiler.java:6464)
    at clojure.lang.Compiler.analyze(Compiler.java:6406)
    at clojure.lang.Compiler$InvokeExpr.parse(Compiler.java:3719)
    at clojure.lang.Compiler.analyzeSeq(Compiler.java:6646)
    at clojure.lang.Compiler.analyze(Compiler.java:6445)
    at clojure.lang.Compiler.analyze(Compiler.java:6406)
    at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:5782)
    at clojure.lang.Compiler$FnMethod.parse(Compiler.java:5217)
    at clojure.lang.Compiler$FnExpr.parse(Compiler.java:3846)
    at clojure.lang.Compiler.analyzeSeq(Compiler.java:6642)
    at clojure.lang.Compiler.analyze(Compiler.java:6445)
    at clojure.lang.Compiler.eval(Compiler.java:6700)
    at clojure.lang.Compiler.eval(Compiler.java:6693)
    at clojure.lang.Compiler.eval(Compiler.java:6692)
    at clojure.lang.Compiler.load(Compiler.java:7130)
    at clojure.lang.Compiler.loadFile(Compiler.java:7086)
    at clojure.main$load_script.invoke(main.clj:274)
    at clojure.main$init_opt.invoke(main.clj:279)
    at clojure.main$initialize.invoke(main.clj:307)
    at clojure.main$null_opt.invoke(main.clj:342)
    at clojure.main$main.doInvoke(main.clj:420)
    at clojure.lang.RestFn.invoke(RestFn.java:421)
    at clojure.lang.Var.invoke(Var.java:383)
    at clojure.lang.AFn.applyToHelper(AFn.java:156)
    at clojure.lang.Var.applyTo(Var.java:700)
    at clojure.main.main(main.java:37)
Caused by: java.lang.ClassNotFoundException: lighttable.nrepl.core
    at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
    at clojure.lang.DynamicClassLoader.findClass(DynamicClassLoader.java:61)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:344)
    at clojure.lang.RT.classForName(RT.java:2065)
    at clojure.lang.Compiler$HostExpr.maybeClass(Compiler.java:978)
    at clojure.lang.Compiler$HostExpr.access$400(Compiler.java:756)
    at clojure.lang.Compiler.analyzeSymbol(Compiler.java:6832)
    at clojure.lang.Compiler.analyze(Compiler.java:6427)
    ... 25 more
clojure.lang.ExceptionInfo: Subprocess failed {:exit-code 1}
    at clojure.core$ex_info.invoke(core.clj:4327)
    at leiningen.core.eval$fn__3532.invoke(eval.clj:226)
    at clojure.lang.MultiFn.invoke(MultiFn.java:231)
    at leiningen.core.eval$eval_in_project.invoke(eval.clj:326)
    at clojure.lang.AFn.applyToHelper(AFn.java:167)
    at clojure.lang.AFn.applyTo(AFn.java:151)
    at clojure.core$apply.invoke(core.clj:619)
    at leiningen.repl$repl.doInvoke(repl.clj:261)
    at clojure.lang.RestFn.invoke(RestFn.java:425)
    at leiningen.light_nrepl$light.doInvoke(light_nrepl.clj:56)
    at clojure.lang.RestFn.invoke(RestFn.java:423)
    at leiningen.light_nrepl$_main.doInvoke(light_nrepl.clj:68)
    at clojure.lang.RestFn.invoke(RestFn.java:397)
    at clojure.lang.AFn.applyToHelper(AFn.java:159)
    at clojure.lang.RestFn.applyTo(RestFn.java:132)
    at leiningen.light_nrepl.main(Unknown Source)
```

**Comment by venantius** [comment]
Looks to be a REPL middleware issue. 

Can you try setting `:ultra {:repl false}`?

I'd be curious if the lighttable folks have any thoughts on this as well.

**Comment by pjagielski** [comment]
Works fine after setting `:repl false`

**Comment by venantius** [comment]
Would you mind updating to Ultra `0.2.1` and seeing if this issue is still persisting? The latest release fixes some nREPL middleware ordering issues that were messing up CIDER and I'm curious if the changes I made will also work for Lighttable.

**Comment by pjagielski** [comment]
Thanks, it works fine now!

**Comment by timothypratley** [comment]
This problem has resurfaced in "0.4.1" (does not happen in "0.3.3"). I have :repl false in my profile.clj

**Comment by venantius** [comment]
Hmm, I can imagine where this is coming from. I'll dig into this.

**Comment by venantius** [comment]
I'm going to flag this issue as `help-wanted` because I'm not a Lighttable user myself and don't have the time to learn a new editor to dig into this.

**Comment by venantius** [comment]
I'm going to close this for now as there doesn't seem to have been further movement on it or any additional complaints. If this is still an issue that people care about then I'll reopen it.
